### ISSUE TITLE
VLC start with GUI, but CUI is more better

### ISSUE THREAD

**Issue by raccy** [tyage/video-player#12]
I play vides with video/audio formats not supported by chromium,
the video-player start the VLC with GUI, and debug console says that it should use `cvlc`.
`cvlc` is not include in VLC, so need to add the following option to start VLC with CUI, 

```
 -I "dummy"
```

I think the CUI mode is better. Do not you think so?

適当すぎる英語を要約すると「-I "dummy"」って付けるとVLCがGUIじゃなくてCUIになるんで、
そっちの方がいいんじゃ無いかな？って事です。

**Comment by tyage** [comment]
@raccy thanks  for your suggestion.
That sounds good to me!
I will work on this issue

**Comment by raccy** [comment]
@tyage thanks for reply and fix
But I think, the fix may be wrong.
You shall rewrite with the following patch.

```diff
-    '-I dummy',
+    '-I',
+    'dummy',
```

Because, the required options are "-I" and "dummy", not "-I dummy".

**Comment by tyage** [comment]
Well, I think this is not a serious problem but your suggestion is better.
Thank you so much!
