### ISSUE TITLE
Change the output type from ogg to webm, or select

### ISSUE THREAD

**Issue by raccy** [tyage/video-player#13]
VLC fails to convert a few videos to ogg, but succeeds convert its to webm.
Webm is more beautiful than ogg, but needs more machine resources to convert.
So, the good idea is that selecting ogg or webm?
If you change ogg to webm, modify the code according to the following line. 

```diff
-`#transcode{vcodec=theo,vb=800,scale=1,acodec=vorb,ab=128,channels=2,samplerate=44100}:http{mux=ogg,dst=:${port}}`,
+`#transcode{vcodec=VP80,vb=800,scale=1,acodec=vorb,ab=128,channels=2,samplerate=44100}:http{mux=ffmpeg{mux=webm},dst=:${port}}`,
```

Failed videos are dumped Niconico live streams with NLE by rtmpdump-nico-live.

**Comment by tyage** [comment]
The idea is looks good to me.
I will add an option to use webm in converting.

Well, any pull request is welcome!

**Comment by tyage** [comment]
It is nice if you show me the video :)
But if you don't feel like to do, you don't have to.

**Comment by raccy** [comment]
@tyage Great!
I can play my video very fine and clear!
