### ISSUE TITLE
Remember controls toggle setting

### ISSUE THREAD

**Issue by kankaristo** [tyage/video-player#17]
When a new video is opened, the controls are hidden, even if they were previously toggled to be visible.

**Comment by tyage** [comment]
That's looks good idea to me!
I will work for it.

**Comment by oxfordyang2016** [comment]
Thank u,this plugin does help me ! can u add the feature,that is ,the player can show caption?

**Comment by tyage** [comment]
@oxfordyang2016 Thanks for your comment, but this issue is not related to video caption.
And it will take some time to consider the design of choosing caption.
But Pull Requests are welcome!
